'use client';

import { makeStyles, tokens } from '@fluentui/react-components';

export default makeStyles({
  card: {
    maxWidth: '100%',
    minWidth: '150px',
    height: '100%',
    cursor: 'pointer',
    backgroundColor: tokens.colorNeutralBackground1,
    borderRadius: tokens.borderRadiusLarge,
    transition: 'all 0.2s ease-in-out',
    display: 'flex',
    flexDirection: 'column',
    boxShadow: 'none',
    ':hover': {
      boxShadow: `0 4px 8px ${tokens.colorNeutralShadowAmbient}`,
    },
    border: `1px solid ${tokens.colorNeutralStroke1}`,
  },
  preview: {
    height: '250px',
    position: 'relative',
    overflow: 'hidden',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: tokens.colorNeutralBackground4,
  },
  imageContainer: {
    position: 'relative',
    width: '100%',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewImage: {
    display: 'block',
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    flexShrink: 0,
    transition: 'opacity 0.3s ease-in-out',
  },
  skeleton: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    backgroundColor: tokens.colorNeutralBackground4,
    animationName: {
      from: { opacity: 0.6 },
      to: { opacity: 1 },
    },
    animationDuration: '1s',
    animationDirection: 'alternate',
    animationIterationCount: 'infinite',
  },
  '@keyframes shimmer': {
    '0%': {
      backgroundPosition: '200% 0',
    },
    '100%': {
      backgroundPosition: '-200% 0',
    },
  },
  content: {
    position: 'relative',
    padding: tokens.spacingVerticalM + ' ' + tokens.spacingHorizontalM,
    height: '45px',
    display: 'flex',
    flexDirection: 'column',
  },
  titleRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  title: {
    fontSize: tokens.fontSizeBase500,
    fontWeight: tokens.fontWeightBold,
    color: tokens.colorNeutralForeground1,
    lineHeight: tokens.lineHeightBase400,
    flex: 1,
  },
  description: {
    fontSize: tokens.fontSizeBase300,
    color: tokens.colorNeutralForeground2,
    paddingTop: tokens.spacingVerticalS,
    lineHeight: tokens.lineHeightBase300,
    display: '-webkit-box',
    WebkitBoxOrient: 'vertical',
    WebkitLineClamp: 2,
    textOverflow: 'ellipsis',
  },
  featuresSection: {
    padding: `0 ${tokens.spacingHorizontalM}`,
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  featuresList: {
    marginTop: tokens.spacingVerticalS,
    overflow: 'hidden',
    listStyleType: 'none',
    padding: 0,
    flex: 1,
    maxHeight: '130px',
    textOverflow: 'ellipsis',
  },
  divider: {
    height: '1px',
    width: '100%',
    backgroundColor: tokens.colorNeutralStroke1,
    margin: `${tokens.spacingVerticalM} 0 ${tokens.spacingVerticalXS} 0`,
    marginBottom: tokens.spacingVerticalM,
  },
  feature: {
    fontSize: tokens.fontSizeBase200,
    color: tokens.colorNeutralForeground2,
    lineHeight: tokens.lineHeightBase200,
    marginBottom: tokens.spacingVerticalL,
    overflow: 'hidden',
    display: '-webkit-box',
    WebkitBoxOrient: 'vertical',
    WebkitLineClamp: 2,
    textOverflow: 'ellipsis',
    '& a': {
      color: tokens.colorBrandForeground1,
      textDecoration: 'none',
      ':hover': {
        textDecoration: 'underline',
      }
    },
    '& code': {
      backgroundColor: tokens.colorNeutralBackground3,
      padding: `${tokens.spacingVerticalXXS} ${tokens.spacingHorizontalXS}`,
      borderRadius: tokens.borderRadiusMedium,
      fontSize: tokens.fontSizeBase100,
      fontFamily: 'monospace',
    },
    '& p': {
      margin: 0,
    }
  },
  tagsSection: {
    padding: `0 ${tokens.spacingHorizontalM}`,
    marginBottom: tokens.spacingVerticalS,
  },
  tags: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: tokens.spacingHorizontalXS,
    marginTop: tokens.spacingVerticalS,
  },
  tag: {
    fontSize: tokens.fontSizeBase100,
    color: tokens.colorNeutralForeground2,
    backgroundColor: tokens.colorNeutralBackground3,
    padding: `${tokens.spacingVerticalXXS} ${tokens.spacingHorizontalXS}`,
    borderRadius: tokens.borderRadiusMedium,
  },
  footer: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingLeft: tokens.spacingHorizontalM,
    paddingRight: tokens.spacingHorizontalM,
    paddingTop: tokens.spacingVerticalM,
    borderTop: `1px solid ${tokens.colorNeutralStroke1}`,
    height: '25px',
  },
  author: {
    display: 'flex',
    alignItems: 'center',
    gap: tokens.spacingHorizontalXS,
  },
  authorText: {
    fontSize: tokens.fontSizeBase200,
    color: tokens.colorNeutralForeground3,
  },
  language: {
    display: 'flex',
    alignItems: 'center',
    gap: tokens.spacingHorizontalXXS,
    marginLeft: tokens.spacingHorizontalS,
  },
  languageDot: {
    width: '8px',
    height: '8px',
    borderRadius: '50%',
  },
  languageText: {
    fontSize: tokens.fontSizeBase200,
    color: tokens.colorNeutralForeground3,
  },
  actionButton: {
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    fontSize: '20px',
    ':hover': {
      color: tokens.colorNeutralForeground1,
    },
  },
  link: {
    textDecoration: 'none',
  },
  playOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'opacity 0.2s ease-in-out',
    zIndex: 1,
    opacity: 1,
    pointerEvents: 'auto',
  },
  playText: {
    color: 'white',
  },
  youtubePlayer: {
    width: '100%',
    position: 'relative',
    paddingTop: '56.25%',
    '& iframe': {
      position: 'absolute',
      top: 0,
      left: 0,
      width: '100%',
      height: '100%',
      border: 'none',
    },
  },
  gifImage: {
    display: 'block',
    maxWidth: '100%',
    maxHeight: 'calc(80vh - 100px)',
    margin: '0 auto',
  },
});
